# Generated by Django 4.1.7 on 2023-03-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='orderes_date',
            new_name='order_date',
        ),
    ]
